### ISSUE TITLE
Infinite flooding in l2_multi

### ISSUE THREAD

**Issue by colin-scott** [noxrepo/pox#43] opened 2013-01-22 05:33 UTC
In both betta and master, l2_multi fails to establish connectivity when run on a full mesh of four switches.

Tested in mininet with the following custom topology:

```
from mininet.topo import Topo

class MyTopo( Topo ):
    def __init__( self, num_switches=4 ):
        # Initialize topology
        Topo.__init__( self )

        switches = [ self.addSwitch('s' + str(switch_id))
                     for switch_id in range(1, num_switches+1) ]
        hosts = [ self.addHost('h' + str(host_id))
                  for host_id in range(1, num_switches+1) ]

        # Connect hosts to switches
        for i, sw in enumerate(switches):
          self.addLink(sw, hosts[i])

        # Connect switches to switches
        for i, switch_i in enumerate(switches):
          for switch_j in switches[i+1:]:
            self.addLink(switch_i, switch_j)

topos = { 'mytopo': ( lambda: MyTopo() ) }
```

Invoked with:

```
sudo mn --custom ~/mininet/custom/topo-2sw-2host.py --topo mytopo --controller=remote,ip=0.0.0.0,port=6633 --mac
```

And:

```
./pox.py --verbose forwarding.l2_multi
```

with Logging.level set to Logging.DEBUG.

It appears that POX floods packets indefinitely, and never learns the correct location for the hosts.

I noticed some strange behavior in l2_multi that might be the cause. Consider a simple case with two switches and two hosts. If host A sends a packet, the first switch will send a PacketIn, and POX will correctly learn that A is attached. It then floods the packet. The weird part is that when the packet arrives at the second switch, POX incorrectly thinks that A has migrated to the second switch... Perhaps this has something to do with why routes are never set up?

**Comment by MurphyMc** [comment] 2013-01-22 06:24
At least one of the problems here is that l2_multi itself does not take any measures to work on looped topologies.  For that matter, the same is also true of a number of other components (e.g., l2_learning and l2_pairs).

The spanning_tree component is meant to be a fairly generic solution to this problem.  However, it hasn't been tested much (or at all?) with l2_multi, since l2_multi doesn't get much love. But I'd suggest that you attempt running your test with spanning_tree as well, because it _definitely_ won't work right without it, and it _may_ work right with it.

The other issue that might be creeping in is if there are broadcasts before discovery figures out the topology.  I believe the problems this causes will eventually sort themselves out when things are operating correctly, but in the presence of loops (especially without spanning_tree), it's never operating correctly.  l2_learning now has a broadcast hold-down to mitigate this problem somewhat, but this hasn't been added to l2_multi (yet?).  If you wait a few seconds for discovery to work before starting tests, that may be enough (though this can be tricky to ensure in the presence of chatty/IPv6 hosts).

A last note is that having unfixed loops (i.e., a looped topology and no spanning_tree) can quite probably lead to a case where discovery _never_ figures out the topology because the network and control channel become entirely saturated with looped packets.

**Comment by MurphyMc** [comment] 2013-01-22 06:39
Just a note that the existence of l2_multi support in samples.spanning_tree indicates that there has been at least a little testing of this scenario. :)

**Comment by MurphyMc** [comment] 2013-01-22 06:48
Another note that this has been added to the FAQ.

**Comment by colin-scott** [comment] 2013-01-23 03:03
Awesome, thanks Murphy!

**Comment by colin-scott** [comment] 2013-01-28 06:12
Hey Murphy,

I tried running spanning_tree alongside l2_multi, and I'm still seeing a loop. 

spanning_tree does indeed stop the flooding loop from occurring, but that seems to be orthogonal to this issue, which involves non-flooded traffic.

It actually converges in Mininet, but it's definitely triggering a loop in STS. I suspect this is because we delay dataplane packets more than Mininet, so we happen to tickle the race condition.

The root cause seems to be in l2_multi itself. Consider this scenario: host A sends a packet, l2_multi learns A's correct location at switch 1, floods the packet, packet ends up at the switch 2, l2_multi learns an _incorrect_ location for A. Then B sends a packet, l2_multi learns correct location for B at switch 2, floods packet, packet arrives at switch 1, l2_multi learns an _incorrect_ location for B. Then the link is discovered. l2_multi decides to set up a route between A and B. It installs flow mods that cause A->B traffic to go from switch 2 to switch 1, and vice versa for B->A. Now when A or B send traffic, it immediately gets caught in a loop, and no PacketIn's are sent until the flow mods time out.

The loop will be remain for ~30 seconds.

I suspect that Mininet converges because it's sending many more packet types than just ICMP, so POX has a chance to correct its mistake when it sees some packet_in's even after the loop has been installed.

You can replay this bug with STS by running:

```
$ git clone git@github.com:ucb-sts/sts.git
$ cd sts
$ git clone -b betta git@github.com:noxrepo/pox.git betta
$ git clone -b debugger git@github.com:noxrepo/pox.git
$ git clone git@github.com:ucb-sts/experiments.git exp
$ ./simulator.py -c exp/loop_4_switches_betta/replay.config
```

**Comment by MurphyMc** [comment] 2013-01-28 16:39
Debugging with the replay is difficult because of persisted code, but almost assuredly, part of the problem is a bug in the debugger and in sts: the software switch (and the OpenFlow transfer function generator thing for HSA) allow an output action to send a packet back out the port it came in on without using OFPP_IN_PORT.  This is against the spec, and may explain why Mininet (OVS) and the simulator work differently.

I've issued ucb-sts/sts#5 on STS and #44 on the debugger branch of POX to correct this.

I think this should at least prevent 2-loops.

Loops of more than two switches, however, can still probably occur.  I think we could further reduce chances by setting the in_ports of each flow mod in l2_multi.  But I think that ultimately, the approach used by l2_multi simply cannot be robust -- you need to add more state on the controller (that is, it's not a fixable bug: it's a basic property of l2_multi).  This is related to what I talked about last year at ONS.  Even adding state at the controller, you still have this sort of problem transiently unless you do some sort of rule versioning (which I've avoided doing in any of the released POX apps so far because I'd like to do it with MPLS).

**Comment by colin-scott** [comment] 2013-01-28 17:15
What do you mean by "persisted code"?

**Comment by MurphyMc** [comment] 2013-01-28 17:22
It looks like there's code in the pickled trace files.  So when I pay them back, I am playing back some mixture of code in the local filesystem and code in the trace.  This may be fine for its intended usage, but as I was trying to debug things by making local changes, it was making things difficult for me.  I attempted to re-run the experiment locally (using the "orig" config file), but at first glance it didn't seem to be working right.  Or wrong in the right way.

**Comment by colin-scott** [comment] 2013-01-28 17:29
The pickled files are dataplane traces. In this case, just a list of packet.icmp.icmp objects.

The "orig" config file generates random inputs, so you'd have to run it a few times to trigger the loop.

Thanks for looking into this!

**Comment by MurphyMc** [comment] 2013-01-28 17:37
Well, I haven't tracked down exactly where, but somewhere... pickled code _from your machine_ seems to sneak in to my interpreter.  I am guessing it's in the traces.  For example, IIRC, when I played back the trace, I got _your_ version of config/fuzz_pox_mesh.py -- not the one on my filesystem.

(This may also have something to do with the problem Andi emailed me about last night.)

**Comment by colin-scott** [comment] 2013-01-28 18:03
Hm? It's automatically generating new config files -- might be what you're seeing.

**Comment by colin-scott** [comment] 2013-01-28 18:05
By the way, I just realized that while your pull request does cause 2-loops to go away, it instead creates blackholes. The switches did indeed have flow_mods that pointed in a loop -- now the behavior is to silently drop packets rather than send them into the loop.

As you said, specifying the in_port in l2_multi should fix that.

**Comment by MurphyMc** [comment] 2013-01-28 20:05
The events trace persists the code of the invariant checking function (looks like maybe Sam wrote the code).  That's what was causing me problems.  Though again, this is probably totally fair considering its usage is to replay the events, not to let you change things after the fact.

**Comment by colin-scott** [comment] 2013-01-29 03:59
Yeah, the invariant checking function is serialized. That said, the function used in this trace invokes HSA with a dynamic import, so you should still be able to modify the behavior of HSA underneath and see the modified output during replay.

**Comment by MurphyMc** [comment] 2013-02-03 03:23
Since I think the second problem turned out to be a bug in the software switch and headerspace analysis, I'm closing this.

(I'm not pushing my fix to the software switch to the betta branch because I'm trying to figure out how we can keep it from diverging even further.)

**Closed as completed by MurphyMc** 2013-02-03 03:23 UTC

**Comment by MurphyMc** [comment] 2013-02-03 03:30
As a note, 118edac42e4f78be6df358c8da1bc746ca54f776 now sets the in_port in l2_multi.
