### ISSUE TITLE
recoco: select error

### ISSUE THREAD

**Issue by backb1** [noxrepo/pox#109] opened 2014-02-21 11:33 UTC
```
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 808, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 761, in run
    self.__target(*self.__args, **self.__kwargs)
  File "[...]/pox/pox/lib/recoco/recoco.py", line 571, in _threadProc
    xl.keys(), timeout )
error: (4, 'Interrupted system call')
```

**Comment by MurphyMc** [comment] 2014-02-22 00:53
Can you provide additional information?
What OS are you running on?
What POX components were you running, and were any of them ones that didn't come with POX?
What was happening when the exception occurred?

**Comment by backb1** [comment] 2014-02-22 01:15
> What OS are you running on?

up-to-date Ubuntu 13.10

> What POX components were you running, and were any of them ones that didn't come with POX?

mylogfilter, log.color, log.level, openflow.of_01, openflow.discovery, misc.full_payload, mycontroller, py

mylogfilter does nothing special. mycontroller also uses this:

```
loop = RecocoIOLoop()
[...]
self.worker = loop.new_worker(some_socket)
self.worker.rx_handler = some_function
```

> What was happening when the exception occurred?

Difficult to say, but I think it tried sending something to the switch. I noticed this error only twice. When I tried to fix it myself I found the following: http://stackoverflow.com/questions/13414029/catch-interrupted-system-call-in-threading#comment18335096_13414029

**Comment by MurphyMc** [comment] 2014-02-22 05:08
Sure; it's easy enough to "fix" the issue by just catching the exception and cycling back through the loop (making sure that the exit condition is checked).  I'm just curious as to why it's happening.  I don't think this issue has ever been reported before, and I've never witnessed it.

The reason for select() getting interrupted should be a signal.  But POX tries not to use any signals and I'd be interested to know where this one is coming from.  Under normal circumstances, sending to a switch happens from the same thread as the select(), so a SIGPIPE sending to a switch wouldn't interrupt it (there's a rare case where the send might happen from another thread in normal operation).

Does your code create any more threads or do any more IO or anything?

**Comment by backb1** [comment] 2014-02-25 11:00
Yes, at the beginning I open a file, but it's already closed after one line (with statement). There's also ZeroMQ which does IO. No threads. I import the following libraries: pickle, pprint, copy, networkx, matplotlib.pyplot, time, json, sys, netaddr, logging, zmq.
I don't use signals in this part of the project.

Can you give me a hint, what further debugging information would be helpful and how to catch it? Then I can add that to my code, so that I have more information about the next exception.

**Comment by MurphyMc** [comment] 2014-03-05 00:31
Hm.  Maybe start by running strace and attempting to look at signals?  Something like...

strace -e trace=none -e signal=all python pox.py ...

**Comment by MurphyMc** [comment] 2014-04-11 22:26
It's been over a month with no new data, so I'm going to close this.  Feel free to reopen if there's new info or advice on how to reproduce this.

**Closed as completed by MurphyMc** 2014-04-11 22:26 UTC
Labels: NeedsReproduction
