### ISSUE TITLE
connect controller to switch

### ISSUE THREAD

**Issue by ebagies** [noxrepo/pox#222] opened 2019-04-08 16:17 UTC
I tried to run the following command: sudo ./pox.py log.level datapaths:icnswitch1
but  i receive the following error:
---------------- INITIALIZING CORE -------------------------
ICN POX 0.2.0 (carp) / Copyright 2011-2013 James McCauley, et al.
POXCORE : Scheduler started
POXCORE : _waiters components
---------------- Returning CORE -------------------------
BOOT : Core is initialized
 --- Raised Content Announcement Event - - 
 ---------------------- MAIN ------------------------ 
 IN BOOT
 BOOT : In _do_launch
 Event :  <class 'pox.core.ComponentRegistered'>
 Event :  <class 'pox.core.ComponentRegistered'>
 Event :  <class 'pox.core.ComponentRegistered'>
 Event :  <class 'pox.core.ComponentRegistered'>
 Event :  <class 'pox.core.ComponentRegistered'>
 Event :  <class 'pox.core.ComponentRegistered'>
 DATAPATH : ICN Switch Function
 DATAPATH : Registering in core
 Event :  <class 'pox.core.ComponentRegistered'>
 Event :  <class 'pox.core.ComponentRegistered'>
 DATAPATH : Gonna call Do Launch
 DATAPATH : IN DO LAUNCH
 Event :  <class 'pox.core.ComponentRegistered'>
 Event :  <class 'pox.core.ComponentRegistered'>
 Event :  <pox.core.GoingUpEvent object at 0x7fe820127990>
 Event :  <pox.core.UpEvent object at 0x7fe820127990>
 OpenFlowWorker 
INFO:dp.00-00-00-00-01-23:Connecting to 127.0.0.1:6633
(' Connecting to %s:%s', '127.0.0.1', 6633)
INFO:core:POX 0.2.0 (carp) is up.
ERROR:openflow.of_01:Error 98 while binding socket: Address already in use
ERROR:openflow.of_01: You may have another controller running.
ERROR:openflow.of_01: Use openflow.of_01 --port=<port> to run POX on another port.
 OpenFlowWorker : _handle_connect 
INFO:dp.00-00-00-00-01-23: Connected to controller

 ***** Connected to controller ******
 ------------------------------------

**Comment by MurphyMc** [comment] 2019-04-08 16:43
This is a fork of POX with which I'm not familiar, but it seems like the problem is a fairly standard one.  Something else is listening on port 6633.  Usually this is another controller, as the error message indicates.  Very often, it's another instance of POX which is also running the openflow.of_01 component with default settings (this is the component which listens for OpenFlow switches to connect -- it's a requirement for OpenFlow-based controllers written in POX).

I'm going to make some guesses here:
* You've already run some sort of "ICN POX" controller
* You're going to run this POX instance as a switch ("datapaths:icnswitch1")
* You might be running further POX instances as other switches (e.g., "datapaths:icnswitch2")

If my guesses are right, only the first one should actually be running the openflow.of_01 component, but it seems like the others are trying to also.  POX generally uses a heuristic to decide whether to automagically start openflow.of_01 or not, and it looks like it's wrong in this case.  The documentation of the POX fork/components you're using should probably have covered this, but... I guess it didn't.

A bad way of resolving the problem might just be to try doing exactly what the error message indicates -- specify a different port for openflow.of_01.  For example:
```
sudo ./pox.py openflow.of_01 --port=6634 datapaths:icnswitch1
```

A better way might be to try to turn off OpenFlow listening altogether.  I don't remember exactly how this works off the top of my head, but I think it might be like:
```
sudo ./pox.py --no-openflow datapaths:icnswitch1
```

Maybe the documentation didn't cover this error because... it's not necessarily actually problematic.  The openflow.of_01 component is failing to start up on this instance of POX, but if this instance of POX is going to be acting as a switch and not as a controller, this might be just fine.

(Sidenote: The log.level invocation in your commandline is meaningless, I believe, because no arguments to it are specified.)

**Comment by ebagies** [comment] 2019-04-09 17:58
Thank you. 
It works with the 1st suggested solution. But why it's not a good solution? and if I tried the 2nd solution, it will be like a legacy switch? or still OpenFlow switch?

**Comment by MurphyMc** [comment] 2019-04-10 01:56
openflow.of_01 is the component that listens to connections *from* switches -- it's used when POX is acting as a controller.  But this instance of POX isn't acting as a controller, so there's no need for it to be running at all.  The first solution prevents the error message by running it on a different port.  There's probably no real harm here, but it's not actually doing anything.  The second solution (I think) will just shut it off, which makes sense since it's not being used anyway.

**Closed as completed by MurphyMc** 2019-04-10 01:56 UTC

**Comment by ebagies** [comment] 2019-04-16 18:42
Thank you very much..

**Comment by EngHassanJ** [comment] 2022-02-12 16:01
it show me this message , can anyone help ? 


tapaths:icnswitch1
POX 0.3.0 (dart) / Copyright 2011-2014 James McCauley, et al.
Module pox.datapaths has no icnswitch1(), but it was specified or passed arguments

**Comment by MurphyMc** [comment] 2022-02-12 21:55
The datapaths:icnswitch1 component is not a part of the original POX distribution -- it is part of some other project that built on top of POX.  If you want to use it, you'll need to find the project it comes from.
