### ISSUE TITLE
Problem in the OpenFlow protocol packing

### ISSUE THREAD

**Issue by damomeen** [noxrepo/pox#65] opened 2013-05-31 10:17 UTC
Hi,

I have downloaded betta branch and have started on Windows7:

python pox.py

Then started the following script (Pox software swich is deployed over real TCP connection to Pox controller):

``` python
# file: dataswitch_test.py

from pox.datapaths.switch import SoftwareSwitch
from pox.datapaths.switch import ofp_hello
from pox.openflow.util import make_type_to_unpacker_table
import logging
import socket
from binascii import hexlify

logging.basicConfig(filename = "pox.log",
                        level    = logging.DEBUG,
                        format   = "%(levelname)s - %(asctime)s - %(name)s - %(message)s")
logger = logging.getLogger("test")

class Connection():

    def __init__(self):
        self.initial_message = "hello"
        HOST, PORT = socket.gethostname(), 6633
        self.unpackers = make_type_to_unpacker_table()
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        self.sock.connect((HOST, PORT))

    def serve(self):
        try:
            while True:
                msg = self.sock.recv(1024)
                print 'Message received', hexlify(msg)

                # OpenFlow parsing occurs here:
                ofp_type = ord(msg[1])
                packet_length = ord(msg[2]) << 8 | ord(msg[3])
                if packet_length > len(msg):
                    break
                new_offset, msg_obj = self.unpackers[ofp_type](msg, 0)
                print ' Decoded OF message is:\n', msg_obj
                self.on_message_received(self, msg_obj)
        finally:
            self.sock.close()

    def set_message_handler(self, handler):
        self.on_message_received = handler

    def send(self, msg):
        print 'OF message to send:\n', msg
        if type(msg) is not bytes:
            if hasattr(msg, 'pack'):
                msg = msg.pack()
        print ' Coded message is', hexlify(msg)
        self.sock.sendall(msg + "\n")

    def set_initial_message(self, msg):
        self.initial_message = msg

if __name__ == "__main__":
    switch = SoftwareSwitch(dpid=1, name="sw1")
    conn = Connection()
    switch.set_connection(conn)
    switch.send_hello()
    conn.serve()
```

It seams that there is some bug in the OpenFlow protocol packing (message generated by Pox soft switch - probably you don't have full unitest coverage in case of software softswitch generated OF messages). You are using Pox softswich without OF message packing to binary format.

> pythonw -u "dataswitch_test.py"
> OF message to send:
> ofp_hello
>   header: 
>     version: 1
>     type:    0 (OFPT_HELLO)
>     length:  8
>     xid:     0
>  Coded message is 0100000800000000
> Message received 0100000800000001
>  Decoded OF message is:
> ofp_hello
>   header: 
>     version: 1
>     type:    0 (OFPT_HELLO)
>     length:  8
>     xid:     1
> Message received 0105000800000002
>  Decoded OF message is:
> ofp_features_request
>   header: 
>     version: 1
>     type:    5 (OFPT_FEATURES_REQUEST)
>     length:  8
>     xid:     2
> OF message to send:
> ofp_features_reply
>   header: 
>     version: 1
>     type:    6 (OFPT_FEATURES_REPLY)
>     length:  224
>     xid:     2
>   datapath_id: 1
>   n_buffers: 100
>   n_tables: 1
>   capabilities: 0
>   actions: 66
>   ports: 
>     port_no: 1
>     hw_addr: 00:00:00:00:01:01
>     name: 00-00-00-00-00-01.1
>     config: 0
>     state: 0
>     curr: 1
>     advertised: 1
>     supported: 1
>     peer: 1
>     port_no: 2
>     hw_addr: 00:00:00:00:01:02
>     name: 00-00-00-00-00-01.2
>     config: 0
>     state: 0
>     curr: 1
>     advertised: 1
>     supported: 1
>     peer: 1
>     port_no: 3
>     hw_addr: 00:00:00:00:01:03
>     name: 00-00-00-00-00-01.3
>     config: 0
>     state: 0
>     curr: 1
>     advertised: 1
>     supported: 1
>     peer: 1
>     port_no: 4
>     hw_addr: 00:00:00:00:01:04
>     name: 00-00-00-00-00-01.4
>     config: 0
>     state: 0
>     curr: 1
>     advertised: 1
>     supported: 1
>     peer: 1
> Traceback (most recent call last):
>   File "dataswitch_test.py", line 58, in <module>
>     conn.serve()
>   File "dataswitch_test.py", line 35, in serve
>     self.on_message_received(self, msg_obj)
>   File "C:\Users\DamianP-PCSS\Downloads\pox-betta\pox-betta\pox\datapaths\switch.py", line 172, in rx_message
>     h(msg, connection=connection)
>   File "C:\Users\DamianP-PCSS\Downloads\pox-betta\pox-betta\pox\datapaths\switch.py", line 212, in _rx_features_request
>     self.send(msg)
>   File "C:\Users\DamianP-PCSS\Downloads\pox-betta\pox-betta\pox\datapaths\switch.py", line 187, in send
>     self._connection.send(message)
>   File "dataswitch_test.py", line 46, in send
>     msg = msg.pack()
>   File "C:\Users\DamianP-PCSS\Downloads\pox-betta\pox-betta\pox\openflow\libopenflow_01.py", line 2036, in pack
>     packed += i.pack()
>   File "C:\Users\DamianP-PCSS\Downloads\pox-betta\pox-betta\pox\openflow\libopenflow_01.py", line 678, in pack
>     assert self._assert()
>   File "C:\Users\DamianP-PCSS\Downloads\pox-betta\pox-betta\pox\openflow\libopenflow_01.py", line 166, in _assert
>     raise RuntimeError(r)
> RuntimeError: name is too long

Is any change this will be corrected?

**Comment by MurphyMc** [comment] 2013-05-31 10:57
Thanks for the good bug report.  I've pushed fixes to the carp branch.

The problem is actually that _generate_port() generated illegal port names, which should now be fixed.
I've also improved the unit test so that it checks packing.

**Closed as completed by MurphyMc** 2013-05-31 10:57 UTC
Labels: Bug, NeedsReproduction, NotABug, MultipleIssues

**Comment by damomeen** [comment] 2013-05-31 12:05
Thank you very much for fast help.

There is probably one additional bug in pox/openflow/of_01.py in "carb" branch in line 766. The buffer sometimes contains the last byte of previous message.

I have changed this line to:

``` python
self.buf = self.buf[offset+1:]
```

and seems to be working via network TCP connection. You can check this by following script (i have added also some debuging in pox/openflow/of_01.py)

``` python
from pox.datapaths.switch import SoftwareSwitch
from pox.datapaths.switch import ofp_hello
from pox.openflow.util import make_type_to_unpacker_table

import logging
import socket
import select
from binascii import hexlify

logging.basicConfig(filename = "pox.log",
                        level    = logging.DEBUG,
                        format   = "%(levelname)s - %(asctime)s - %(name)s - %(message)s")
logger = logging.getLogger("test")

#========================================================================================================
class Connection():

    def __init__(self):
        HOST, PORT = socket.gethostname(), 6633
        self.unpackers = make_type_to_unpacker_table()
        self.sock = socket.socket(socket.AF_INET, socket.SOCK_STREAM)
        #self.sock.settimeout(1)
        self.sock.connect((HOST, PORT))

    def serve(self):
        '''reads messages from TCP client socket and pass them to SoftwareSwitch until OF controller will close the connection'''
        try:
            while True:
                # Await a read event
                rlist, wlist, elist = select.select( [self.sock], [], [], 15)
                # Test for timeout
                if [rlist, wlist, elist] == [ [], [], [] ]:
                    print "Five seconds elapsed.\n"
                    continue
                # Loop through each socket in rlist, read and print the available data
                for sock in rlist:
                    msg = sock.recv(8192)
                print 'Message received', hexlify(msg)

                if msg == "":
                    print 'Shutting down.'
                    break

                # OpenFlow parsing occurs here:
                ofp_type = ord(msg[1])
                packet_length = ord(msg[2]) << 8 | ord(msg[3])
                if packet_length > len(msg):
                    break
                new_offset, msg_obj = self.unpackers[ofp_type](msg, 0)
                print ' Decoded OF message is:\n', msg_obj
                self.on_message_received(self, msg_obj)
        finally:
            self.sock.close()

    def set_message_handler(self, handler):
        '''method used by SoftwareSwitch to register handler for incoming OF messages'''
        self.on_message_received = handler

    def send(self, msg):
        '''method used by SoftwareSwitch to send OF messages 
        to OF controller through existing client socket connection'''
        print 'OF message to send:\n', msg
        if type(msg) is not bytes:
            if hasattr(msg, 'pack'):
                msg = msg.pack()
        print ' Coded message is', hexlify(msg)
        self.sock.sendall(msg + "\n")

#========================================================================================================
if __name__ == "__main__":
    switch = SoftwareSwitch(dpid=1, name="sw1")
    conn = Connection()
    switch.set_connection(conn)
    switch.send_hello()
    conn.serve()
```

Regards,
Damian

**Comment by MurphyMc** [comment] 2013-05-31 13:28
I believe the bug here is with your Connection class.  Your send() method is appending a newline, but the OpenFlow spec does not have newlines between messages.  I am guessing the extra character you're seeing in the unpacking is, in fact, this newline.

**Comment by damomeen** [comment] 2013-05-31 13:50
Ok. You are right..I forgot to remove this newline.

I'm trying a new thing...I'm connecting yours SoftwareSwitch to Floodlight but after Hello and Features exchanges and waiting 20 sec Floodlight terminates the connection saying that OpenFlow handshake was not finalized. Do you know something about this?

> OF message to send:
> ofp_hello
>   header: 
>     version: 1
>     type:    0 (OFPT_HELLO)
>     length:  8
>     xid:     0
>  Coded message is 0100000800000000
> Message received 0100000800000000
>  Decoded OF message is:
> ofp_hello
>   header: 
>     version: 1
>     type:    0 (OFPT_HELLO)
>     length:  8
>     xid:     0
> Message received 0105000800000000
>  Decoded OF message is:
> ofp_features_request
>   header: 
>     version: 1
>     type:    5 (OFPT_FEATURES_REQUEST)
>     length:  8
>     xid:     0
> OF message to send:
> ofp_features_reply
>   header: 
>     version: 1
>     type:    6 (OFPT_FEATURES_REPLY)
>     length:  224
>     xid:     0
>   datapath_id: 1
>   n_buffers: 100
>   n_tables: 1
>   capabilities: 0
>   actions: 66
>   ports: 
>     port_no: 1
>     hw_addr: 00:00:00:00:01:01
>     name: 000000000001.1
>     config: 0
>     state: 0
>     curr: 1
>     advertised: 1
>     supported: 1
>     peer: 1
>     port_no: 2
>     hw_addr: 00:00:00:00:01:02
>     name: 000000000001.2
>     config: 0
>     state: 0
>     curr: 1
>     advertised: 1
>     supported: 1
>     peer: 1
>     port_no: 3
>     hw_addr: 00:00:00:00:01:03
>     name: 000000000001.3
>     config: 0
>     state: 0
>     curr: 1
>     advertised: 1
>     supported: 1
>     peer: 1
>     port_no: 4
>     hw_addr: 00:00:00:00:01:04
>     name: 000000000001.4
>     config: 0
>     state: 0
>     curr: 1
>     advertised: 1
>     supported: 1
>     peer: 1
>  Coded message is 010600e00000000000000000000000010000006401000000000000000000004200010000000001013030303030303030303030312e31000000000000000000000000000100000001000000010000000100020000000001023030303030303030303030312e32000000000000000000000000000100000001000000010000000100030000000001033030303030303030303030312e33000000000000000000000000000100000001000000010000000100040000000001043030303030303030303030312e340000000000000000000000000001000000010000000100000001

Select timeout elapsed.

Shutting down.

**Comment by MurphyMc** [comment] 2013-05-31 14:11
As far as I know, the handshake is the exchange of hellos and feature request/reply, which seems to be complete.

Maybe they're expecting the switch to send echo requests?  In your select timeout (where you print "Five seconds elapsed."), try sending an ofp_echo_request.

Incidentally, we are now way off the topic of this issue and into the realm of general discussion.  If possible, my preference is for such discussion to take place on the POX forum or (better yet) the pox-dev mailing list, both of which are at noxrepo.org.
